### ISSUE TITLE
Colorblind comparing in shaders

### ISSUE THREAD

**Issue by KoBeWi** [Spooner/ashton#35]
I made a shader that checks if pixel has a given color and if yes, it replaces it with another one (so basically a color replacement). The issue is that it doesn't work for all colors. OpenGL ignores some colors as if it couldn't see them. Example one is RGB: 0/91/32 (and even ones with similar values).
Below the example shader and program. Link to example: https://www.dropbox.com/s/sjkw70bjsdzpde4/colorblind.zip?dl=0

Shader code:
```C
uniform sampler2D in_Texture;

varying vec2 var_TexCoord;

void main()
{
  vec4 color = texture2D(in_Texture, var_TexCoord);
  
  vec4 test1 = vec4(0.0/255.0, 91.0/255.0, 32.0/255.0, 1); //the bugged color
  vec4 test2 = vec4(44.0/255.0, 210.0/255.0, 190.0/255.0, 1); //random working color
  
  if (color == test1) {
    gl_FragColor = vec4(1,1,1,1); //change to white if green
    return;
  }
  else if (color == test2) {
    gl_FragColor = vec4(0,0,0,1); //change to black if cyan
    return;
  }
  else
    gl_FragColor = color;
}
```
Program code:
```ruby
require 'gosu'
require 'ashton'
include Gosu

class GameWindow < Gosu::Window
  def initialize
    super(640, 480, false)
    self.caption = "Test Game"
    
    @image = Image.new(self,'image.png')
    
    shader = Ashton::Shader.new(fragment: "shader.frag") #initialize shader
    
    new=Ashton::Texture.new(@image.width,@image.height) #make a texture for processing
    shader.enable
    new.render{@image.draw(0,@image.height,0,1,-1)} #draw image on texture using shader
    shader.disable
    @image=new.to_image #replace old image with new one
  end

  def draw
    @image.draw(32,32,0) #draw the resulting image
    #cyan (44,210,190) is replaced with black
    #green (0,91,32) is replaced with wh... oh ,wait. It's not replaced :(
  end
end

GameWindow.new.show
```
Original image:
![image](https://cloud.githubusercontent.com/assets/2223172/5413783/e182c6ee-8219-11e4-824b-f88d010c0ae1.png)

Result:
![result](https://cloud.githubusercontent.com/assets/2223172/5413806/033342d2-821a-11e4-9679-b0711256ba52.png)

Concluson: it replaces one of colors (bottom-right), but can't change the one in background.
My specs: Win 7 x64 GeForce GT540M

**Comment by Spooner** [comment]
I've merged the 4fv "hack". Feel free to give me a 3fv pull request too.

**Comment by Spooner** [comment]
I should close this though, since the issue was with rounding by GLSL, not Ashton.
